apiVersion: apps/v1
kind: Deployment
metadata:
  name: spamham-deployment
  labels:
    app: spamham
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spamham
  template:
    metadata:
      labels:
        app: spamham
    spec:
      containers:
      - name: spamham
        resources: {}
        image: tobiaspottier/spamhamdet:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: spamham-service
spec:
  type: NodePort
  selector:
    app: spamham
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31007
